### ISSUE TITLE
Not Darken Hero Image Option

### ISSUE THREAD

**Issue by tsressin** [USACE/groundwork#114]
I would like to see the option of darkening or not darkening a hero image added.

We have these pretty photos to show on the landing page and darkening them ruins it, IMO.

**Comment by willbreitkreutz** [comment]
I think we can make this optional, could do a parameter for how dark to make it, like 0 - 1 (why you would go all the way who know)

**Comment by LaurenAllin** [comment]
I agree that an option to not darken the Hero Image would be nice.
