### ISSUE TITLE
Sidebar Popout Menu Stays Open When Item Selected

### ISSUE THREAD

**Issue by tsressin** [USACE/groundwork#126]
I'm not sure if this is intended behavior or not.

I noticed that popout menus from the sidebar stay open after an item is selected.  This ends up blocking some of the content of the page that renders on that click.

Personally, I would like to see the popout menu go away when clicked.

![image](https://github.com/user-attachments/assets/26b9ff0a-72cb-4fc2-82b9-bc8461c42cec)

**Comment by krowvin** [comment]
Tom, this is certainly a bug (not intended behavior). Not sure how I missed this!
