### ISSUE TITLE
Allow tabs select to be targeted outside the component

### ISSUE THREAD

**Issue by krowvin** [USACE/groundwork#136]
See if we can add a param or something to let us target the select on the tabs with external JS to the tab component.

https://github.com/USACE/groundwork/blob/main/lib/components/navigation/tabs.jsx#L11

Cheesy workaround for now:
```javascript
useEffect(()=> {
    setTimeout(()=> {
        document.querySelectorAll('[role="tab"]').forEach(t=> {
        if (t.innerText.toLowerCase() == _basin.toLowerCase())
        t.click()
        })
    }, 1000)
}, [])
```

EDIT: Click handler would be useful as well to avoid doing this:

```javascript
 t.addEventListener("click", (e)=> {
                console.log("click!" + _basin)
                doUpdateUrlWithBase(`/gage-data?basin=${e.target.innerText.toLowerCase()}`)
            })
```

**Comment by willbreitkreutz** [comment]
I think we could add an `onClick` to the tab component to allow arbitrary code to be run when a tab is selected.
