### ISSUE TITLE
Documentation: Site Wrapper

### ISSUE THREAD

**Issue by jeffsuperglide** [USACE/groundwork#14]
Copy button for example code results in `undefined` when trying to paste into an IDE.

Also, `headerLinks` or `links` for SiteWrapper prop?

```
import { SiteWrapper } from "@usace/groundwork";
import { useConnect } from "redux-bundler-hook";

const links = [{ id: "docs", text: "Documentation", href: "/docs" }];

function App() {
  const {
    route: Route,
  } = useConnect("selectRoute");

  return (
      <SiteWrapper headerLinks={links}>
        <Route />
      </SiteWrapper>
  );
}

export default App;
```

**Comment by willbreitkreutz** [comment]
> Also, headerLinks or links for SiteWrapper prop?

Used to be `headerLinks` updated to be `links` but need to double check that the docs got updated too.
