### ISSUE TITLE
User Configuration Options

### ISSUE THREAD

**Issue by jbkolze** [USACE/groundwork#26]
A streamlined process for ingesting user-supplied configuration options should be developed.

The primary identified use case is for setting a user-defined CDA URL to use rather than the default provided by groundwork.  Currently, this is allowed through the passing of a property (GROUNDWORK_CDA_URL) set on the global window object -- not ideal.

Another potential use case would be to set a default "office" parameter for CDA calls, as this will generally be set to the same value in 100% of a WM office's CDA requests.

**Comment by willbreitkreutz** [comment]
@jbkolze does this issue move to the wm-components lib?

**Comment by jbkolze** [comment]
@willbreitkreutz Probably.  There could potentially be some other style/layout-based options in groundwork, but the only current use case I have in mind is for something like setting the site-wide API URL for data retrieval, which is obviously a data need and, hence, groundwork-water.

Don't think we can transfer between orgs (without some "creativity") so can just close this and re-open there as far as I'm concerned.
