### ISSUE TITLE
Add docs for "friends of groundwork"

### ISSUE THREAD

**Issue by jbkolze** [USACE/groundwork#42]
Add documentation for other recommended libraries / frameworks that play nicely with groundwork.

One example would be [React Icons](https://react-icons.github.io/react-icons/)

**Comment by willbreitkreutz** [comment]
Yup, related to #43

**Comment by krowvin** [comment]
+https://github.com/USACE-WaterManagement/groundwork-water WIP

**Comment by adamscarberry** [comment]
Would suggestion the auxiliary libraries like https://github.com/USACE-WaterManagement/groundwork-water be mentioned in the top level readme to it's right in your face when visiting the repo.
