### ISSUE TITLE
Add how to get icons to the documentation 

### ISSUE THREAD

**Issue by krowvin** [USACE/groundwork#43]
Discussed in the workshop that users would appreciate how to add icons, and which icon library, to use for icons while developing with groundwork.

**Comment by willbreitkreutz** [comment]
+1

**Comment by krowvin** [comment]
I've been suggesting [`react-icons`](https://react-icons.github.io/react-icons) to users. Want to confirm here that we will be suggesting just one library and react-icons is sufficient? 

Alternatively could use font-awesome or Hero [or some other icon library for React](https://www.reddit.com/r/reactjs/comments/xj8q1y/what_is_your_favorite_icon_set_for_react/)

**Comment by willbreitkreutz** [comment]
I think `react-icons` is the right place to start, it includes FA and lots of others
