### ISSUE TITLE
Header Nav Max Width instead of fluid

### ISSUE THREAD

**Issue by adamscarberry** [USACE/groundwork#46]
I'm working on porting A2W to use groundwork.

I need the header nav to have a max width and not stretch across the entire width (especially on large screens).

The USACE HQ site is also fixed with a max width.

Example shown below:

![image](https://github.com/USACE/groundwork/assets/46494851/10c59136-3151-4b18-b980-5c7fdc2b8658)

I have started this modification to groundwork, but struggling to get all the details working correctly.  Before continuing I wanted to get consensus if this sounds ok or if this is the wrong direction.

cc @willbreitkreutz

**Comment by willbreitkreutz** [comment]
I think add a `fluid-nav` prop to the SiteWrapper to make it opt-in for full width similar to `Container`

**Comment by willbreitkreutz** [comment]
but yeah, default it to a constrained with is fine, do you want me to take a look at how?

@adamscarberry

**Comment by adamscarberry** [comment]
@willbreitkreutz If you think you have a quick way to make the adjustments, go for it.  It seemed more complicated when I got into it.

**Comment by willbreitkreutz** [comment]
@adamscarberry i'll give it a go

**Comment by adamscarberry** [comment]
@willbreitkreutz   If you get into it and wish you hadn't :-). I can push what I have as a branch.  It's just a bit messy at the moment.

**Comment by willbreitkreutz** [comment]
@adamscarberry yeah, not as straightforward as I thought it would be, got it working for the header, need to modify the footer next

**Comment by willbreitkreutz** [comment]
Woo, footer was actually easy since I was already using the `Container` element in there...
