### ISSUE TITLE
remove plotly from groundwork

### ISSUE THREAD

**Issue by adamscarberry** [USACE/groundwork#70]
based on https://github.com/USACE/groundwork/issues/59 remove added bloat plotly creates.

Potentially add it to another groundwork spinoff library.

**Comment by adamscarberry** [comment]
@willbreitkreutz Can this be removed from groundwork?  Anything holding it up?

**Comment by willbreitkreutz** [comment]
@adamscarberry just need to take the time to do it

**Comment by krowvin** [comment]
Will I went ahead and did this - tried to save you some time

**Comment by krowvin** [comment]
Making a note of this in here for later.

i think if we added plotly to the external option for rollup in the vite.config.js that it would have **reduced** our bundle size. 

Looking through my commits when removing it I never saw it in this line
https://github.com/USACE/groundwork/blob/819f43a412786a0d28e26d146b73a6995cbfbe7d/vite.config.js#L24
