### ISSUE TITLE
Add width breakpoints for the header/footer 

### ISSUE THREAD

**Issue by krowvin** [USACE/groundwork#81]
A user brought up to me that the header always aligns left no matter what the page size is. 

On ultrawide or larger screens this can appear unnatural. 

Suggesting we add the breakpoints to match the "USACE Theme" that AFPIMS uses. For the *footer* and *header*

The <Container> component does do this with "fluid" when you leave it off/false it centers the _page_ content. But not the navigation (headers/footer).

Examples
Header
![image](https://github.com/USACE/groundwork/assets/23619282/914c83df-fcbd-4446-bd0f-2d76da6243bd)
Footer
![image](https://github.com/USACE/groundwork/assets/23619282/b65dbcdf-d969-45c2-8edb-55890e48ff98)

**Comment by adamscarberry** [comment]
This is a2w on an ultrawide monitor.  I'm not seeing the issue.

<img width="1601" alt="image" src="https://github.com/USACE/groundwork/assets/46494851/21b58e9a-f2dd-4c07-8e55-eda832023d88">

**Comment by krowvin** [comment]
Must make sure to not add `fluid` to the `<Container />`
