### ISSUE TITLE
Sidebar Mobile and Popout

### ISSUE THREAD

**Issue by krowvin** [USACE/groundwork#89]
On the AFPIMS sites it looks like they have a fly out menu, and they also turn into a select menu on mobile. 

We need this for district sites that have navigation content in the sidebar that is not a duplicate of the header like Groundworks doc site is. 

I know some users have expressed interest in this. This looks like a good option. For now I think just 1 level deep? Same structure our header has with the children key.

**Comment by krowvin** [comment]
Agreed on 1 level deep, use the simple component in tailwindui

**Comment by LaurenAllin** [comment]
I am running into issues with the sidebar on mobile. The sidebar formats fine in the browser version, but overlaps with the breadcrumbs and also does not show a user where to click to expand the navigation menu. (Groundwork 3.4.0)
<img width="289" alt="SidebarMobile" src="https://github.com/user-attachments/assets/b7949597-73e3-4052-a1a5-25c0c9d7508d">
<img width="1265" alt="SideBarBrowser" src="https://github.com/user-attachments/assets/c0f1610b-9d83-409a-8222-eb912da20753">

**Comment by krowvin** [comment]
I took a look at your TestBranchNAB - this looks to be where you were having the issue?

I was able to replicate your issue that you sent in the screenshot. However, I do not think this is related to the `<Sidebar />` component itself. 

I added the breakpoint `md:` to the front of `grid:` and it fixed the sidebar. 
Line  12 of your `src/app-apages/home/index.jsx` should be:
```jsx
      <div className="md:grid grid-cols-12 gap-6">
```

The `md:` tells the grid to only be a grid when the page is medium or larger. (i.e. 768px)

You can read about breakpoints and responsive design for TaildwindCSS [here](https://tailwindcss.com/docs/responsive-design)

Report back if this fixes it for you!
